name: Weekly Rotation Schedule

on:
  workflow_dispatch: # Manual trigger

jobs:
  update-rotation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - uses: pnpm/action-setup@v2
        with:
          version: '10'
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Run rotation script
        run: pnpm tsx src/index.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
